version: '2.28.1'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-celery
    ports:
      - "5672:5672"   # RabbitMQ port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  celery:
    build:
      context: ./app
    container_name: celery
    command: celery -A celery_batch worker --concurrency=1 --loglevel=info -P eventlet
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@127.0.0.1:5672/celery_vhost
      - CELERY_RESULT_BACKEND=rpc://127.0.0.1:6379

  client:
    build:
      context: ./app
    container_name: client
    command: python run.py
    depends_on:
      - celery
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@54.85.40.192:5672/celery_vhost
      - CELERY_RESULT_BACKEND=rpc://127.0.0.1:6379
