version: '2.4'

services:
  celery:
    build:
      context: ./app
    container_name: celery-celerydemo
    command: celery -A celery_batch worker --concurrency=1 --loglevel=info -P eventlet
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@<your_rabbitmq_host>:5672/celery_vhost
      - CELERY_RESULT_BACKEND=rpc://

  client:
    build:
      context: ./app
    container_name: client-celerydemo
    command: python run.py
    depends_on:
      - celery
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@<your_rabbitmq_host>:5672/celery_vhost
      - CELERY_RESULT_BACKEND=rpc://
